version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  build:
    working_directory: '~/dmn-vendor-wrapper'
    parallelism: 1
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install --no-save
      - run:
          name: Build Dist
          command: |
            npm run build
  deploy-master:
    working_directory: '~/dmn-vendor-wrapper'
    machine: true
    steps:
      - checkout
      - aws-s3/sync:
          from: '~/dmn-vendor-wrapper/dist'
          to: 's3://dmn-sitemap-data-ww/sd/vendor'
          arguments: |
            --acl public-read \
            --cache-control "max-age=600" \
            --exclude="*.circleci/*" \
            --exclude=".gitignore" \
            --exclude="*.DS_Store/*" \
            --exclude="*.git/*"
          overwrite: true

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy-master:
          requires:
            - build
          filters:
            branches:
              only: master

